# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Executing remote ssh commands using password for stage
        uses: appleboy/ssh-action@master
        if: contains ('refs/heads/master', github.ref)
        with:
          host: ${{ secrets.HOST_STAGE }}
          username: ${{ secrets.USERNAME_STAGE }}
          password: ${{ secrets.PASSWORD_STAGE }}
          debug: true
          script: |
            cd www/krion.little-about-web.top/downloads/
            git pull origin main
            echo "I just pulled stage here $(date)" » CD. log
